sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.4.2"
      env: TOXENV=py34
    - python: "3.4.2"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      sudo: true
      dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: tox
